AllCops:
  TargetRubyVersion: 2.3

# not sure if mandatory spacing is important
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false

# caring about '' or "" seems overly pedantic
Style/StringLiterals:
  Enabled: false

# caring about formalizing names of single line block params is dumb
Style/SingleLineBlockParams:
  Enabled: false

# mandated sprintf, format over String#%
Style/FormatString:
  Enabled: false
