language: ruby

# Ruby version is specified by .ruby-version in the root of this repo. If we ever
# need to test multiple versions, we'll need to add them explicitly to this list:
# rvm: [ 2.3 ]

cache:
  directories:
     - /home/travis/.rvm/

before_install:
  - gem update --system
  - gem install bundler:$(cat .bundler-version)

script:
  - bundle exec rubocop
  - bundle exec rspec
  - |
    if grep -A1 'BUNDLED WITH' Gemfile.lock | grep $(cat .bundler-version) >/dev/null; then
      echo ".bundler-version matches Gemfile.lock's BUNDLED WITH version"
    else
      echo ".bundler-version $(cat .bundler-version) doesn't match Gemfile.lock's BUNDLED WITH version:"
      grep -A1 'BUNDLED WITH' Gemfile.lock
      echo "Run 'bundle update --bundler' to update Gemfile.lock"
      exit 1
    fi
